### ISSUE TITLE
ebcli is failing out with "Error initializing DB: resource temporarily unavailable"

### ISSUE THREAD

**Issue by njmurarka** [cosmos/peggy#109] opened 2019-12-12 05:56 UTC
Hello.

I am trying to use ebcli to burn tokens that have been or will be unlocked onto Ethereum, with the following command:

ebcli tx ethbridge burn cosmos1py2hyelc8lwqfm44wtjdfe3gq6vhlrykhaw4gz 0xBe4680d29AC7129D0Db45E4017DD146579a6C931 1000000000000000000blz --token-contract-address=0x75E6f42Daba0e300287f14e99086104820582D34 --ethereum-chain-id=3 --from=validator --chain-id=mychain --yes

Unfortunately, and rather non-deterministically, this command will sometimes (it sometimes succeeds too!) fail with the following error:

failed to get from fields: couldn't create db: Error initializing DB: resource temporarily unavailable

I see this error alot across the board, and seem to recall seeing it being output from the ebrelayer as well. It seems to be a cause of a large number of problems, as we will sometimes be able to do tests and sometimes, not. 

Any thoughts here? Which "DB" is this? I suspect it is the blockchain's database, but am unsure. 

I get this error quite a bit if I want to run a relayer but am already running the REST-server, as follows: 

ebcli rest-server --laddr=tcp://<private ip:1317> --chain-id=<my_chain_id>

If I am running the REST-server and get that error when running the relayer, I am forced to kill the REST-server, to get further. 

Please share your thoughts.

**Comment by denalimarsh** [comment] 2019-12-13 04:04
Thank you for opening this well-described issue.

This is a known error that was recently introduced. It occurs because an active process has a lock on the database, preventing other processes from accessing it. In the ebrelayer, the error on `ebcli tx ethbridge burn` is addressed and fixed in PR https://github.com/cosmos/peggy/pull/106 by combining what were independent processes into a unified relayer service. The PR is currently under review, so if you're able to reproduce the error from that branch please start a review/leave a comment on the PR with steps to reproduce.

**Closed** 2020-04-14 01:27 UTC
