### ISSUE TITLE
In the new commits why validator deifinition is removed.It was present in earlier version of peggy

### ISSUE THREAD

**Issue by apatifirstblood** [cosmos/peggy#78] opened 2019-10-14 09:42 UTC
Earlier we had to define the validator separately with the commission rates and all other characteristics.In the present version there is no mention of Validator credentials.
I think this might be the reason there is issue with the relayer and smart contract connection.
Can anybody please put some light on this.. 

**Earlier peggy**

ebcli tx staking create-validator \
  --amount=100000000stake \
  --pubkey=$(ebd tendermint show-validator) \
  --moniker="test_moniker" \
  --chain-id=testing \
  --commission-rate="0.10" \
  --commission-max-rate="0.20" \
  --commission-max-change-rate="0.01" \
  --min-self-delegation="1" \
  --gas=200000 \
  --gas-prices="0.001stake" \
  --from=validator
# Then wait 10 seconds then confirm your validator was created correctly, and has become Bonded status
ebcli query staking validators --trust-node

in present peggy this has been removed ..why?????

**Comment by musnit** [comment] 2019-10-14 09:49
Duplicate of https://github.com/cosmos/peggy/issues/73#issuecomment-541286718 - see response there

**Closed by musnit** 2019-10-14 09:49 UTC

**Comment by apatifirstblood** [comment] 2019-10-15 06:45
Got it...still in which part code for set up for 1 validator is done in the peggy module..i.e where the below are defined inn the code.
--commission-rate="0.10"
--commission-max-rate="0.20"
--commission-max-change-rate="0.01"
